# A Github actions workflow to run tests on a push or pull request
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      # Setup Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache build dependencies
      - name: Cache build dependencies
        id: cache-build-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-build-deps
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      # Write the secret TEST_ROBLOSECURITY to roblosecurity.txt
      - name: Write roblosecurity.txt
        run: echo "${{ secrets.TEST_ROBLOSECURITY }}" > roblosecurity.txt
      # Write the secret TEST_ROBLOSECURITY to roblosecurity.txt
      - name: Write proxy.txt
        run: echo "${{ secrets.TEST_PROXY }}" > proxy.txt

      # Run tests
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test